dataset_path: declare-lab/PuzzleVQA
dataset_kwargs:
  token: True
task: "puzzlevqa"
test_split: train
output_type: generate_until
doc_to_visual: !function utils.puzzlevqa_doc_to_visual
doc_to_text: !function utils.puzzlevqa_doc_to_text
doc_to_target: "answer"
# The return value of process_results will be used by metrics
process_results: !function utils.puzzlevqa_process_results
# Note that the metric name can be either a registed metric function (such as the case for GQA) or a key name returned by process_results
metric_list:
  - metric: gpt_eval_score
    aggregation: !function utils.puzzlevqa_aggregate_results
    higher_is_better: true

lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "\nAnswer with the option's letter from the given choices."

